// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbkuvytrvfywsnslvjos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impia3V2eXRydmZ5d3Nuc2x2am9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjEzMzAsImV4cCI6MjA2MDI5NzMzMH0.28F031_L6mIdfAEaO-8LYdB-0wM8DJiGiD6CaYqxnmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);